import React, { useState } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { Search, Eye, Download, FileText, PieChart as PieChartIcon, BarChart2 } from 'lucide-react';
import { motion } from 'framer-motion';
import { PieChart, Pie, Cell, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import Pagination from '../../components/Pagination';

const MOCK_INVOICES = [
  { id: 'INV-2041', amount: '₦50,000', description: 'Monthly Security Dues', date: '2026-05-01', dueDate: '2026-05-15', status: 'unpaid' },
  { id: 'INV-2040', amount: '₦20,000', description: 'Facility Maintenance', date: '2026-04-01', dueDate: '2026-04-15', status: 'paid' },
  { id: 'INV-2039', amount: '₦15,000', description: 'Waste Disposal', date: '2026-03-01', dueDate: '2026-03-15', status: 'paid' },
  { id: 'INV-2038', amount: '₦10,000', description: 'Late Payment Fee', date: '2026-02-15', dueDate: '2026-02-28', status: 'overdue' },
  { id: 'INV-2037', amount: '₦50,000', description: 'Monthly Security Dues', date: '2026-02-01', dueDate: '2026-02-15', status: 'paid' },
];

const STATUS_COLORS = {
  paid: { bg: '#f0fdf4', color: '#16a34a' },
  unpaid: { bg: '#fffbeb', color: '#d97706' },
  overdue: { bg: 'var(--bg-danger-subtle)', color: '#dc2626' },
};

const CHART_COLORS = {
  paid: 'var(--text-success)',
  unpaid: '#f59e0b',
  overdue: 'var(--text-danger)'
};

const Invoices = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const role = location.pathname.split('/')[1];

  const [search, setSearch] = useState('');
  const [filterStatus, setFilterStatus] = useState('all');
  const [currentPage, setCurrentPage] = useState(1);
  const pageSize = 5;

  const filtered = MOCK_INVOICES.filter(i => {
    if (filterStatus !== 'all' && i.status !== filterStatus) return false;
    const q = search.toLowerCase();
    if (q && !i.id.toLowerCase().includes(q) && !i.description.toLowerCase().includes(q)) return false;
    return true;
  });

  const paginated = filtered.slice((currentPage - 1) * pageSize, currentPage * pageSize);

  // Prepare Pie Chart Data (grouped by status)
  const pieData = [
    { name: 'Paid', value: MOCK_INVOICES.filter(i => i.status === 'paid').length },
    { name: 'Unpaid', value: MOCK_INVOICES.filter(i => i.status === 'unpaid').length },
    { name: 'Overdue', value: MOCK_INVOICES.filter(i => i.status === 'overdue').length },
  ];

  // Prepare Bar Chart Data (generated by month in current year)
  // Hardcoded for demo purposes (using actual dates from mock would be more complex)
  const barData = [
    { name: 'Jan', count: 0 },
    { name: 'Feb', count: 2 },
    { name: 'Mar', count: 1 },
    { name: 'Apr', count: 1 },
    { name: 'May', count: 1 },
    { name: 'Jun', count: 0 },
  ];

  return (
    <div className="inv-page">
      <div className="inv-header">
        <div>
          <h1>Invoices</h1>
          <p>Manage and track your property bills and invoices.</p>
        </div>
      </div>

      <div className="inv-analytics-grid">
        <div className="inv-chart-card">
          <h3 className="inv-chart-title"><PieChartIcon size={18} /> Invoices by Status</h3>
          <div className="inv-chart-content">
            <ResponsiveContainer width="100%" height={220}>
              <PieChart>
                <Pie 
                  data={pieData} 
                  cx="50%" 
                  cy="50%" 
                  innerRadius={60}
                  outerRadius={80} 
                  paddingAngle={5}
                  dataKey="value"
                >
                  {pieData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={CHART_COLORS[entry.name.toLowerCase()]} />
                  ))}
                </Pie>
                <Tooltip 
                  contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 4px 12px rgba(0,0,0,0.1)' }}
                  itemStyle={{ fontWeight: 600 }}
                />
              </PieChart>
            </ResponsiveContainer>
            <div className="inv-chart-legend">
              {pieData.map(d => (
                <div key={d.name} className="legend-item">
                  <div className="legend-color" style={{ background: CHART_COLORS[d.name.toLowerCase()] }} />
                  <span>{d.name} ({d.value})</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="inv-chart-card">
          <h3 className="inv-chart-title"><BarChart2 size={18} /> Invoices Generated (2026)</h3>
          <div className="inv-chart-content">
            <ResponsiveContainer width="100%" height={240}>
              <BarChart data={barData} margin={{ top: 20, right: 20, left: -20, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--border-default)" />
                <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: 'var(--text-tertiary)' }} dy={10} />
                <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: 'var(--text-tertiary)' }} />
                <Tooltip 
                  cursor={{ fill: 'var(--bg-muted)' }}
                  contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 4px 12px rgba(0,0,0,0.1)' }}
                />
                <Bar dataKey="count" fill="#0ea5e9" radius={[4, 4, 0, 0]} barSize={32} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      <div className="inv-controls">
        <div className="inv-search">
          <Search size={16} />
          <input 
            placeholder="Search by invoice ID or description..." 
            value={search} 
            onChange={e => { setSearch(e.target.value); setCurrentPage(1); }} 
          />
        </div>
        <div className="inv-status-tabs">
          {['all', 'unpaid', 'paid', 'overdue'].map(status => (
            <button 
              key={status} 
              className={`inv-tab ${filterStatus === status ? 'active' : ''}`} 
              onClick={() => { setFilterStatus(status); setCurrentPage(1); }}
            >
              {status.charAt(0).toUpperCase() + status.slice(1)}
            </button>
          ))}
        </div>
      </div>

      <div className="inv-table-card">
        <div style={{ overflowX: 'auto' }}>
          <table className="inv-table">
            <thead>
              <tr>
                <th>Invoice ID</th>
                <th>Description</th>
                <th>Amount</th>
                <th>Date Issued</th>
                <th>Due Date</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {paginated.map((inv, index) => {
                const sc = STATUS_COLORS[inv.status] || {};
                return (
                  <motion.tr 
                    key={inv.id} 
                    initial={{ opacity: 0, y: 10 }} 
                    animate={{ opacity: 1, y: 0 }} 
                    transition={{ delay: index * 0.05 }}
                  >
                    <td>
                      <div className="inv-id-col">
                        <FileText size={16} color="var(--text-tertiary)" />
                        <span style={{ fontWeight: 700 }}>{inv.id}</span>
                      </div>
                    </td>
                    <td style={{ fontWeight: 600 }}>{inv.description}</td>
                    <td style={{ fontWeight: 800, color: 'var(--bg-brand)' }}>{inv.amount}</td>
                    <td style={{ color: 'var(--text-tertiary)' }}>{inv.date}</td>
                    <td style={{ color: 'var(--text-tertiary)' }}>{inv.dueDate}</td>
                    <td>
                      <span className="inv-status-badge" style={{ background: sc.bg, color: sc.color }}>
                        {inv.status.toUpperCase()}
                      </span>
                    </td>
                    <td>
                      <div className="inv-actions">
                        <button 
                          className="inv-btn-view" 
                          onClick={() => navigate(`/${role}/invoices/${inv.id}`)}
                          title="View Details"
                        >
                          <Eye size={16} /> View
                        </button>
                      </div>
                    </td>
                  </motion.tr>
                );
              })}
              {paginated.length === 0 && (
                <tr>
                  <td colSpan="7" style={{ textAlign: 'center', padding: '3rem', color: 'var(--text-quaternary)' }}>
                    No invoices found.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
        {filtered.length > 0 && (
          <div style={{ marginTop: '1.5rem' }}>
            <Pagination 
              currentPage={currentPage} 
              totalCount={filtered.length} 
              pageSize={pageSize} 
              onPageChange={setCurrentPage} 
              onPageSizeChange={() => {}} 
            />
          </div>
        )}
      </div>

      <style jsx>{`
        .inv-page { display: flex; flex-direction: column; gap: 1.5rem; padding-bottom: 3rem; }
        .inv-header { display: flex; justify-content: space-between; align-items: flex-start; }
        .inv-header h1 { font-size: 1.75rem; font-weight: 800; color: var(--text-primary); margin-bottom: 0.25rem; }
        .inv-header p { color: var(--text-tertiary); }
        .inv-controls { display: flex; gap: 1rem; flex-wrap: wrap; align-items: center; }
        .inv-analytics-grid { display: grid; grid-template-columns: 1fr 2fr; gap: 1.5rem; margin-bottom: 1rem; }
        .inv-chart-card { background: var(--bg-surface); border: 1px solid var(--border-default); border-radius: 16px; padding: 1.5rem; }
        .inv-chart-title { font-size: 1rem; font-weight: 700; color: var(--text-primary); margin: 0 0 1rem 0; display: flex; align-items: center; gap: 0.5rem; }
        .inv-chart-content { display: flex; flex-direction: column; align-items: center; }
        .inv-chart-legend { display: flex; gap: 1rem; flex-wrap: wrap; justify-content: center; margin-top: 0.5rem; }
        .legend-item { display: flex; align-items: center; gap: 0.4rem; font-size: 0.8rem; font-weight: 600; color: var(--text-tertiary); }
        .legend-color { width: 10px; height: 10px; border-radius: 50%; }
        .inv-search { flex: 1; min-width: 250px; display: flex; align-items: center; gap: 0.75rem; background: var(--bg-surface); padding: 0.75rem 1rem; border: 1px solid var(--border-default); border-radius: 10px; color: var(--text-quaternary); }
        .inv-search input { flex: 1; border: none; outline: none; background: none; font-size: 0.875rem; color: var(--text-primary); }
        .inv-status-tabs { display: flex; gap: 0.5rem; flex-wrap: wrap; }
        .inv-tab { background: var(--bg-surface); border: 1px solid var(--border-default); padding: 0.5rem 1.25rem; border-radius: 8px; font-size: 0.8125rem; font-weight: 600; color: var(--text-tertiary); cursor: pointer; transition: all 0.2s; }
        .inv-tab.active { background: var(--bg-brand); color: var(--text-inverse); border-color: var(--bg-brand); }
        .inv-table-card { background: var(--bg-surface); border: 1px solid var(--border-default); border-radius: 16px; padding: 1.5rem; }
        .inv-table { width: 100%; border-collapse: collapse; min-width: 800px; }
        .inv-table th { padding: 0.875rem 0; font-size: 0.75rem; font-weight: 600; color: var(--text-quaternary); border-bottom: 1px solid var(--bg-muted); text-align: left; text-transform: uppercase; letter-spacing: 0.05em; }
        .inv-table td { padding: 1rem 0; font-size: 0.875rem; border-bottom: 1px solid var(--bg-subtle); color: var(--text-primary); }
        .inv-table tbody tr:last-child td { border-bottom: none; }
        .inv-id-col { display: flex; align-items: center; gap: 0.5rem; }
        .inv-status-badge { padding: 4px 12px; border-radius: 20px; font-size: 0.7rem; font-weight: 800; letter-spacing: 0.05em; }
        .inv-actions { display: flex; gap: 0.5rem; }
        .inv-btn-view { background: var(--bg-subtle); border: 1px solid var(--border-default); padding: 0.5rem 0.75rem; border-radius: 8px; font-weight: 600; color: var(--bg-brand); cursor: pointer; display: flex; align-items: center; gap: 0.4rem; transition: background 0.2s; }
        .inv-btn-view:hover { background: var(--border-default); }
        @media (max-width: 900px) {
          .inv-analytics-grid { grid-template-columns: 1fr; }
        }
        @media (max-width: 768px) {
          .inv-controls { flex-direction: column; align-items: stretch; }
          .inv-search { width: 100%; }
          .inv-status-tabs { overflow-x: auto; -webkit-overflow-scrolling: touch; padding-bottom: 4px; }
          .inv-table-card { padding: 1rem; }
        }
      `}</style>
    </div>
  );
};

export default Invoices;
